from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)

# ---------------------------------------------------------------------------
# CapabilityBroker: preserve unsupported ordinary writers on the existing
# legacy completion-cleared path and translate expected Program routing errors
# into structured capability results.
# ---------------------------------------------------------------------------
path = Path("packages/host-runtime/src/capability-broker.ts")
text = path.read_text()
text = replace_once(
    text,
    '''import {\n  resolveCurrentProgramOperationContext,\n  type ProgramRootOperationAuthorityV1,\n} from "./program-dispatch.ts";\n''',
    '''import {\n  ProgramDispatchControlError,\n  ProgramDispatchStaleError,\n  resolveCurrentProgramOperationContext,\n  type ProgramRootOperationAuthorityV1,\n} from "./program-dispatch.ts";\n''',
    "Program routing error imports",
)
text = replace_once(
    text,
    '''    const quiescenceBinding = workspaceAccessClass === "may_write" ? operationScopedQuiescence(capability) : undefined;\n\n    const verificationPlan = await this.cognition.matchVerification(\n''',
    '''    const quiescenceBinding = workspaceAccessClass === "may_write" ? operationScopedQuiescence(capability) : undefined;\n    // Existing uncontained ordinary writers remain pre-baseline/legacy until their\n    // adapter declares a supported containment contract. Program may_write still\n    // routes as may_write and is rejected before operation.requested below.\n    const persistedWorkspaceAccessClass =\n      workspaceAccessClass !== "may_write" || quiescenceBinding !== undefined\n        ? workspaceAccessClass\n        : undefined;\n\n    const verificationPlan = await this.cognition.matchVerification(\n''',
    "persisted access compatibility decision",
)
text = replace_once(
    text,
    '''          isReadOnly,\n          workspaceAccessClass,\n          workspaceAccessClassifier: { id: "host-capability-workspace-access-v1", version: 1 },\n          ...(quiescenceContract !== undefined ? { quiescenceContract } : {}),\n''',
    '''          isReadOnly,\n          ...(persistedWorkspaceAccessClass !== undefined ? {\n            workspaceAccessClass: persistedWorkspaceAccessClass,\n            workspaceAccessClassifier: { id: "host-capability-workspace-access-v1", version: 1 },\n          } : {}),\n          ...(quiescenceContract !== undefined ? { quiescenceContract } : {}),\n''',
    "conditional persisted access metadata",
)
old_route = '''    let pre: PersistedDomainEvent<string, unknown>[];\n    let program: ProgramCapabilityOperationContextV1 | null = null;\n    if (this.programOperationAuthority !== undefined) {\n      const routed = await this.programOperationAuthority.appendRoutedRootOperation({\n        sessionId: request.sessionId,\n        operationId: operationId as string,\n        workspaceAccessClass,\n        ...(request.program !== undefined ? { program: request.program } : {}),\n        drafts: preDrafts,\n      });\n      if (routed.status === "program_may_write_blocked") {\n        if (quiescenceBinding === undefined) {\n          return this.finish(request, {\n            outcome: "denied",\n            errorCode: "program_quiescence_unsupported",\n            error: `Program-linked may_write capability lacks a supported operation-scoped quiescence contract: ${request.toolName}`,\n          });\n        }\n        return this.finish(request, {\n          outcome: "denied",\n          errorCode: "program_mutation_settlement_pending",\n          error: "Program-linked may_write execution remains non-admitting until confirmed-effect generation advancement and post-quiescence observation settlement are installed",\n        });\n      }\n      pre = routed.events;\n      program = routed.program;\n    } else {\n      if (request.program !== undefined) {\n        return this.finish(request, {\n          outcome: "denied",\n          errorCode: "program_operation_authority_unavailable",\n          error: "Explicit Program operation context requires protected Program operation authority",\n        });\n      }\n      const routed = await this.admission.enqueue(async () => {\n        const currentProgram = await resolveCurrentProgramOperationContext(this.store, request.sessionId);\n        if (currentProgram !== null) return { status: "program_authority_required" as const };\n        return { status: "appended" as const, events: await this.store.append(preDrafts) };\n      });\n      if (routed.status === "program_authority_required") {\n        return this.finish(request, {\n          outcome: "denied",\n          errorCode: "program_operation_authority_unavailable",\n          error: "An active ProgramAttempt requires protected Program operation authority",\n        });\n      }\n      pre = routed.events;\n    }\n'''
new_route = '''    let pre: PersistedDomainEvent<string, unknown>[];\n    let program: ProgramCapabilityOperationContextV1 | null = null;\n    try {\n      if (this.programOperationAuthority !== undefined) {\n        const routed = await this.programOperationAuthority.appendRoutedRootOperation({\n          sessionId: request.sessionId,\n          operationId: operationId as string,\n          workspaceAccessClass,\n          ...(request.program !== undefined ? { program: request.program } : {}),\n          drafts: preDrafts,\n        });\n        if (routed.status === "program_may_write_blocked") {\n          if (quiescenceBinding === undefined) {\n            return this.finish(request, {\n              outcome: "denied",\n              errorCode: "program_quiescence_unsupported",\n              error: `Program-linked may_write capability lacks a supported operation-scoped quiescence contract: ${request.toolName}`,\n            });\n          }\n          return this.finish(request, {\n            outcome: "denied",\n            errorCode: "program_mutation_settlement_pending",\n            error: "Program-linked may_write execution remains non-admitting until confirmed-effect generation advancement and post-quiescence observation settlement are installed",\n          });\n        }\n        pre = routed.events;\n        program = routed.program;\n      } else {\n        if (request.program !== undefined) {\n          return this.finish(request, {\n            outcome: "denied",\n            errorCode: "program_operation_authority_unavailable",\n            error: "Explicit Program operation context requires protected Program operation authority",\n          });\n        }\n        const routed = await this.admission.enqueue(async () => {\n          const currentProgram = await resolveCurrentProgramOperationContext(this.store, request.sessionId);\n          if (currentProgram !== null) return { status: "program_authority_required" as const };\n          return { status: "appended" as const, events: await this.store.append(preDrafts) };\n        });\n        if (routed.status === "program_authority_required") {\n          return this.finish(request, {\n            outcome: "denied",\n            errorCode: "program_operation_authority_unavailable",\n            error: "An active ProgramAttempt requires protected Program operation authority",\n          });\n        }\n        pre = routed.events;\n      }\n    } catch (error) {\n      if (error instanceof ProgramDispatchStaleError) {\n        return this.finish(request, {\n          outcome: "stale",\n          errorCode: "program_execution_stale",\n          error: error.message,\n        });\n      }\n      if (error instanceof ProgramDispatchControlError) {\n        return this.finish(request, {\n          outcome: "denied",\n          errorCode: "program_operation_invalid",\n          error: error.message,\n        });\n      }\n      throw error;\n    }\n'''
text = replace_once(text, old_route, new_route, "structured Program routing result")
path.write_text(text)

# ---------------------------------------------------------------------------
# Targeted regressions.
# ---------------------------------------------------------------------------
path = Path("packages/host-runtime/src/program-operation-correlation.test.ts")
text = path.read_text()
needle = '''  it("keeps supported Program may_write non-admitting until effect/base settlement is installed", async () => {\n'''
stale_test = '''  it("returns structured stale when protected Program observation is unavailable", async () => {\n    const runtime = await setup("19", { name: "inspect", workspaceAccessClass: "read_only", async execute() { return { result: {}, outcome: "succeeded" }; } });\n    const unavailable = new ProgramDispatchServiceV1({\n      store: runtime.locked.store,\n      admission: runtime.admission,\n      workspaceCoordinator: { runExclusive: (work) => work() },\n      observations: { observe: async () => ({ status: "unknown" as const, reason: "tracker unavailable" }) },\n      agentGenerations: { isCurrent: (_sessionId, generation) => generation === 7 },\n      recovery: { isClear: () => true },\n      firstDispatchPlanning: { recheckAcceptedPlanningBase: async () => {} },\n    });\n    runtime.broker.setProgramOperationAuthority(unavailable);\n    const before = (await replay(runtime.locked)).filter((event) => event.type === "operation.requested").length;\n    const result = await runtime.broker.execute({ sessionId: runtime.session.sessionId, toolCallId: "tc-stale-result", toolName: "inspect", args: {} });\n    expect(result).toMatchObject({ outcome: "stale", errorCode: "program_execution_stale" });\n    expect((await replay(runtime.locked)).filter((event) => event.type === "operation.requested")).toHaveLength(before);\n    runtime.locked.close();\n  });\n\n'''
text = replace_once(text, needle, stale_test + needle, "structured stale regression")
needle2 = '''  it("does not turn a completed legacy pre-baseline writer into a permanent barrier", async () => {\n'''
ordinary_test = '''  it("keeps an unsupported ordinary writer on the legacy completion-cleared path", async () => {\n    const suffix = "20";\n    const dir = mkdtempSync(join(tmpdir(), "alcode-program-operation-ordinary-writer-"));\n    dirs.push(dir);\n    const locked = await openLockedWorkspaceStore({ databasePath: join(dir, "workspace.sqlite"), lockPath: join(dir, "workspace.lock"), workspaceId: "018f0000-0000-7000-8000-000000000520", repositoryId: "program-operation-ordinary-writer" });\n    const admission = new CanonicalAdmissionQueue(locked.store);\n    const sessions = new HostSessionManager(locked, admission);\n    const session = await sessions.openOrResume();\n    const initial = program(session.sessionId, suffix);\n    await admission.append([{ eventId: mkEventId(), workspaceId: asWorkspaceId(locked.store.workspaceId), sessionId: session.sessionId, programStateId: asEventProgramStateId(String(initial.programStateId)), occurredAt: new Date().toISOString(), type: "program.created", payload: { state: initial }, payloadSchemaVersion: 1, producer: { kind: "runtime", component: "ordinary-writer-test" } }]);\n    const current = base(locked.store.workspaceId);\n    const dispatch = new ProgramDispatchServiceV1({ store: locked.store, admission, workspaceCoordinator: { runExclusive: (work) => work() }, observations: { observe: async () => ({ status: "complete" as const, base: current }) }, agentGenerations: { isCurrent: (_sessionId, generation) => generation === 7 }, recovery: { isClear: () => true }, firstDispatchPlanning: { recheckAcceptedPlanningBase: async () => {} } });\n    const broker = new CapabilityBroker(locked.store, admission, new CognitionGateway(locked), new DefaultHostPolicy({ knownTools: ["mutate"], allowMutations: true }), [{ name: "mutate", isReadOnly: false, async execute() { return { result: {}, outcome: "succeeded" }; } }]);\n    broker.setProgramOperationAuthority(dispatch);\n    const mutation = await broker.execute({ sessionId: session.sessionId, toolCallId: "tc-ordinary-writer", toolName: "mutate", args: {} });\n    expect(mutation.outcome).toBe("succeeded");\n    const requested = (await replay(locked)).find((event) => event.type === "operation.requested");\n    expect((requested?.payload as Record<string, unknown>).workspaceAccessClass).toBeUndefined();\n    const issued = await dispatch.issueAttempt({ programStateId: String(initial.programStateId), expectedProgramRevision: initial.revision, workItemId: "work-20", sessionId: session.sessionId, agentGeneration: 7 });\n    expect(issued.status).toBe("issued");\n    locked.close();\n  });\n\n'''
text = replace_once(text, needle2, ordinary_test + needle2, "ordinary unsupported writer regression")
path.write_text(text)
