from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)

# Canonical operations projection: add explicit reconciliation outcomes.
path = Path("packages/storage/src/operations.ts")
text = path.read_text()
text = replace_once(
    text,
    '''  {\n    name: "update-interrupted",\n    sql: `UPDATE operations SET effect_status = 'indeterminate',\n      reconciliation_status = 'pending'\n      WHERE operation_id = ?\n        AND lifecycle_state IN ('requested', 'started')\n        AND reconciliation_status = 'not_required'`,\n  },\n];''',
    '''  {\n    name: "update-interrupted",\n    sql: `UPDATE operations SET effect_status = 'indeterminate',\n      reconciliation_status = 'pending'\n      WHERE operation_id = ?\n        AND lifecycle_state IN ('requested', 'started')\n        AND reconciliation_status = 'not_required'`,\n  },\n  {\n    name: "update-reconciliation-resolved",\n    sql: `UPDATE operations SET effect_status = ?, reconciliation_status = 'resolved'\n      WHERE operation_id = ?\n        AND effect_status = 'indeterminate'\n        AND reconciliation_status IN ('pending', 'unresolved')`,\n  },\n  {\n    name: "update-reconciliation-unresolved",\n    sql: `UPDATE operations SET reconciliation_status = 'unresolved'\n      WHERE operation_id = ?\n        AND effect_status = 'indeterminate'\n        AND reconciliation_status = 'pending'`,\n  },\n];''',
    "reconciliation statements",
)
text = replace_once(
    text,
    '''export interface OperationInterruptedPayload {\n  operationId: string;\n}\n\n// ---------------------------------------------------------------------------\n// Projection definition''',
    '''export interface OperationInterruptedPayload {\n  operationId: string;\n}\n\n/** Host-admitted reconciliation proved whether a previously indeterminate effect occurred. */\nexport interface OperationReconciliationResolvedPayload {\n  operationId: string;\n  effectStatus: "confirmed" | "absent";\n  evidenceDigest: string;\n  reconciliationContractId: string;\n  reconciliationContractVersion: number;\n}\n\n/** Host-admitted reconciliation ran but could not prove the external effect. */\nexport interface OperationReconciliationUnresolvedPayload {\n  operationId: string;\n  evidenceDigest: string;\n  reconciliationContractId: string;\n  reconciliationContractVersion: number;\n}\n\nfunction assertReconciliationAuthority(\n  payload: OperationReconciliationResolvedPayload | OperationReconciliationUnresolvedPayload,\n): void {\n  if (payload.evidenceDigest.length === 0 || payload.reconciliationContractId.length === 0 ||\n      !Number.isSafeInteger(payload.reconciliationContractVersion) || payload.reconciliationContractVersion <= 0) {\n    throw new OperationStateError("operation reconciliation lacks bounded versioned Host evidence authority");\n  }\n}\n\n// ---------------------------------------------------------------------------\n// Projection definition''',
    "reconciliation payloads",
)
text = replace_once(
    text,
    ''' * Handles four event types:\n *   operation.requested → insert with lifecycle_state='requested'\n *   operation.started → update to 'started'\n *   operation.completed → update to 'terminal' with outcome × effect × reconciliation\n *   operation.interrupted → one-way not_required→pending for crash survivors\n */''',
    ''' * Handles operation lifecycle plus canonical reconciliation facts:\n *   operation.requested → insert with lifecycle_state='requested'\n *   operation.started → update to 'started'\n *   operation.completed → update to 'terminal' with outcome × effect × reconciliation\n *   operation.interrupted → one-way not_required→pending for crash survivors\n *   operation.reconciliation.resolved → indeterminate pending/unresolved → confirmed|absent + resolved\n *   operation.reconciliation.unresolved → indeterminate pending → unresolved\n */''',
    "projection docs",
)
text = replace_once(
    text,
    '''        case "operation.interrupted": {\n          const p = event.payload as OperationInterruptedPayload;\n          const changes = tx.exec("update-interrupted", p.operationId);\n          if (changes !== 1) {\n            throw new OperationStateError(\n              `operation.interrupted for ${p.operationId}: expected 1 row updated, got ${changes}. ` +\n              "Operation may not exist, may already be terminal, or may already be pending.",\n            );\n          }\n          break;\n        }\n\n        default:''',
    '''        case "operation.interrupted": {\n          const p = event.payload as OperationInterruptedPayload;\n          const changes = tx.exec("update-interrupted", p.operationId);\n          if (changes !== 1) {\n            throw new OperationStateError(\n              `operation.interrupted for ${p.operationId}: expected 1 row updated, got ${changes}. ` +\n              "Operation may not exist, may already be terminal, or may already be pending.",\n            );\n          }\n          break;\n        }\n\n        case "operation.reconciliation.resolved": {\n          const p = event.payload as OperationReconciliationResolvedPayload;\n          assertReconciliationAuthority(p);\n          if (p.effectStatus !== "confirmed" && p.effectStatus !== "absent") {\n            throw new OperationStateError("resolved reconciliation must prove effect confirmed or absent");\n          }\n          const changes = tx.exec("update-reconciliation-resolved", p.effectStatus, p.operationId);\n          if (changes !== 1) {\n            throw new OperationStateError(\n              `operation.reconciliation.resolved for ${p.operationId}: operation is not indeterminate pending/unresolved`,\n            );\n          }\n          break;\n        }\n\n        case "operation.reconciliation.unresolved": {\n          const p = event.payload as OperationReconciliationUnresolvedPayload;\n          assertReconciliationAuthority(p);\n          const changes = tx.exec("update-reconciliation-unresolved", p.operationId);\n          if (changes !== 1) {\n            throw new OperationStateError(\n              `operation.reconciliation.unresolved for ${p.operationId}: operation is not indeterminate pending`,\n            );\n          }\n          break;\n        }\n\n        default:''',
    "reconciliation apply cases",
)
path.write_text(text)

# Export canonical payload contracts.
path = Path("packages/storage/src/index.ts")
text = path.read_text()
text = replace_once(
    text,
    '''  type OperationInterruptedPayload,\n  OperationStateError,''',
    '''  type OperationInterruptedPayload,\n  type OperationReconciliationResolvedPayload,\n  type OperationReconciliationUnresolvedPayload,\n  OperationStateError,''',
    "storage exports",
)
path.write_text(text)

# Focused state-machine proofs.
path = Path("packages/storage/src/operations.test.ts")
text = path.read_text()
anchor = '''  // 12. Default mapping function correctness\n  it("12: defaultEffectStatus and defaultReconciliationStatus", () => {\n    expect(defaultEffectStatus("succeeded", false)).toBe("confirmed");\n    expect(defaultEffectStatus("failed", false)).toBe("indeterminate");\n    expect(defaultEffectStatus("cancelled", false)).toBe("indeterminate");\n    expect(defaultEffectStatus("timed_out", false)).toBe("indeterminate");\n    expect(defaultEffectStatus("succeeded", true)).toBe("not_applicable");\n\n    expect(defaultReconciliationStatus("confirmed")).toBe("not_required");\n    expect(defaultReconciliationStatus("absent")).toBe("not_required");\n    expect(defaultReconciliationStatus("not_applicable")).toBe("not_required");\n    expect(defaultReconciliationStatus("indeterminate")).toBe("pending");\n  });'''
replacement = anchor + '''\n\n  it("13: reconciliation can prove an indeterminate effect confirmed", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n      makeOperationDraft(opId, "operation.completed", { operationId: opId, outcome: "failed", isReadOnly: false }),\n      makeOperationDraft(opId, "operation.reconciliation.resolved", {\n        operationId: opId, effectStatus: "confirmed", evidenceDigest: "sha256:confirmed",\n        reconciliationContractId: "bash-reconcile-v1", reconciliationContractVersion: 1,\n      }),\n    ]);\n    const op = createOperationQuery(db).getById(opId)!;\n    expect(op.effectStatus).toBe("confirmed");\n    expect(op.reconciliationStatus).toBe("resolved");\n  });\n\n  it("14: insufficient reconciliation preserves indeterminate effect as unresolved", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n      makeOperationDraft(opId, "operation.started", { operationId: opId }),\n      makeOperationDraft(opId, "operation.interrupted", { operationId: opId }),\n      makeOperationDraft(opId, "operation.reconciliation.unresolved", {\n        operationId: opId, evidenceDigest: "sha256:insufficient",\n        reconciliationContractId: "bash-reconcile-v1", reconciliationContractVersion: 1,\n      }),\n    ]);\n    const op = createOperationQuery(db).getById(opId)!;\n    expect(op.effectStatus).toBe("indeterminate");\n    expect(op.reconciliationStatus).toBe("unresolved");\n  });\n\n  it("15: unresolved reconciliation may later resolve from stronger evidence", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n      makeOperationDraft(opId, "operation.completed", { operationId: opId, outcome: "timed_out", isReadOnly: false }),\n      makeOperationDraft(opId, "operation.reconciliation.unresolved", {\n        operationId: opId, evidenceDigest: "sha256:first",\n        reconciliationContractId: "bash-reconcile-v1", reconciliationContractVersion: 1,\n      }),\n      makeOperationDraft(opId, "operation.reconciliation.resolved", {\n        operationId: opId, effectStatus: "absent", evidenceDigest: "sha256:stronger",\n        reconciliationContractId: "bash-reconcile-v1", reconciliationContractVersion: 1,\n      }),\n    ]);\n    const op = createOperationQuery(db).getById(opId)!;\n    expect(op.effectStatus).toBe("absent");\n    expect(op.reconciliationStatus).toBe("resolved");\n  });'''
text = replace_once(text, anchor, replacement, "positive reconciliation tests")
invalid_anchor = '''  // 5. duplicate operation.requested → throws (INSERT not INSERT OR REPLACE)\n  it("duplicate requested → throws (strict insert)", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n    ]);\n    await expect(appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n    ])).rejects.toThrow();\n  });'''
invalid_replacement = invalid_anchor + '''\n\n  it("reconciliation cannot rewrite an already certain effect", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n      makeOperationDraft(opId, "operation.completed", { operationId: opId, outcome: "succeeded", isReadOnly: false }),\n    ]);\n    await expect(appendAndCatchUp([\n      makeOperationDraft(opId, "operation.reconciliation.resolved", {\n        operationId: opId, effectStatus: "absent", evidenceDigest: "sha256:nope",\n        reconciliationContractId: "bash-reconcile-v1", reconciliationContractVersion: 1,\n      }),\n    ])).rejects.toThrow();\n    expect(createOperationQuery(db).getById(opId)?.effectStatus).toBe("confirmed");\n  });\n\n  it("reconciliation rejects missing versioned evidence authority", async () => {\n    const opId = mkOperationId() as string;\n    await appendAndCatchUp([\n      makeOperationDraft(opId, "operation.requested", { operationId: opId, toolName: "bash", args: {}, isReadOnly: false }),\n      makeOperationDraft(opId, "operation.completed", { operationId: opId, outcome: "failed", isReadOnly: false }),\n    ]);\n    await expect(appendAndCatchUp([\n      makeOperationDraft(opId, "operation.reconciliation.unresolved", {\n        operationId: opId, evidenceDigest: "", reconciliationContractId: "", reconciliationContractVersion: 0,\n      }),\n    ])).rejects.toThrow("versioned Host evidence authority");\n  });'''
text = replace_once(text, invalid_anchor, invalid_replacement, "negative reconciliation tests")
path.write_text(text)

print("Applied canonical operation reconciliation slice")
