// Ouroboros golden differential — compares TS reducer output against
// actual Python-generated Ouroboros golden output.
//
// The golden file at fixtures/ouroboros-golden.json was generated by running
// the pinned Ouroboros oracle (commit 20be4b18) against the same event inputs.
// The TS port must produce identical graph structure (node IDs, kinds, labels,
// edge sources/targets/kinds) for each family.

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  reduceStream,
  reduceEvent,
  createReasoningGraph,
  deriveNodeId,
  getEdgesByKind,
  EdgeKind as EK,
  NodeKind as NK,
  type ReasoningNode,
} from "./index.ts";

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "fixtures");
const golden = JSON.parse(readFileSync(join(FIXTURES_DIR, "ouroboros-golden.json"), "utf-8"));

function tsGraphToComparable(graph: ReturnType<typeof createReasoningGraph>) {
  return {
    nodes: [...graph.nodes.values()].map((n) => ({
      id: n.id,
      kind: n.kind,
      label: n.label,
    })).sort((a, b) => a.id.localeCompare(b.id)),
    edges: [...graph.edges.values()].map((e) => ({
      source: e.source,
      target: e.target,
      kind: e.kind,
    })).sort((a, b) =>
      a.source.localeCompare(b.source) ||
      a.target.localeCompare(b.target) ||
      a.kind.localeCompare(b.kind),
    ),
  };
}

// Ouroboros uses capitalized kind values (Objective, Hypothesis, etc.) in
// its StrEnum. ALCODE uses lowercase. Map for comparison.
const KIND_MAP: Record<string, string> = {
  "Objective": "objective",
  "Hypothesis": "hypothesis",
  "Falsifier": "falsifier",
  "Observation": "observation",
  "FalsifierEvaluation": "falsifier_evaluation",
};

function normalizeGoldenNode(node: { id: string; kind: string; label: string }) {
  return { ...node, kind: KIND_MAP[node.kind] ?? node.kind.toLowerCase() };
}

describe("golden: normal flow (Ouroboros oracle)", () => {
  it("objective + hypothesis with falsifier produces matching graph", () => {
    const events = [
      { sequence: 1, type: "objective", payload: { statement: "fix the bug" } },
      { sequence: 2, type: "hypothesis", payload: {
        claim: "null pointer on line 42",
        falsifier: "no crash after fix",
        objectiveId: "event:s:1:objective",
      } },
    ];
    const ts = tsGraphToComparable(reduceStream("s", events as never));
    const py = {
      nodes: golden.families.normal_flow.nodes.map(normalizeGoldenNode),
      edges: golden.families.normal_flow.edges,
    };
    expect(ts.nodes).toEqual(py.nodes);
    expect(ts.edges).toEqual(py.edges);
  });
});

describe("golden: replay/duplicate (Ouroboros oracle)", () => {
  it("two independent replays produce identical graphs", () => {
    const events = [
      { sequence: 1, type: "objective", payload: { statement: "fix the bug" } },
      { sequence: 2, type: "hypothesis", payload: {
        claim: "null pointer on line 42",
        falsifier: "no crash after fix",
        objectiveId: "event:s:1:objective",
      } },
    ];
    const g1 = reduceStream("s", events as never);
    const g2 = reduceStream("s", events as never);
    expect(tsGraphToComparable(g1)).toEqual(tsGraphToComparable(g2));
    // Also matches the Python golden
    const py = {
      nodes: golden.families.replay_a.nodes.map(normalizeGoldenNode),
      edges: golden.families.replay_a.edges,
    };
    expect(tsGraphToComparable(g1)).toEqual(py);
  });
});

describe("golden: event-prefix reconstruction (Ouroboros oracle)", () => {
  it("prefix of 1 event = just objective", () => {
    const ts = tsGraphToComparable(reduceStream("s", [
      { sequence: 1, type: "objective", payload: { statement: "fix the bug" } },
    ] as never));
    const py = {
      nodes: golden.families.prefix1.nodes.map(normalizeGoldenNode),
      edges: golden.families.prefix1.edges,
    };
    expect(ts).toEqual(py);
  });

  it("prefix of 2 events = objective + hypothesis with falsifier", () => {
    const ts = tsGraphToComparable(reduceStream("s", [
      { sequence: 1, type: "objective", payload: { statement: "fix the bug" } },
      { sequence: 2, type: "hypothesis", payload: {
        claim: "null pointer on line 42",
        falsifier: "no crash after fix",
        objectiveId: "event:s:1:objective",
      } },
    ] as never));
    const py = {
      nodes: golden.families.prefix2.nodes.map(normalizeGoldenNode),
      edges: golden.families.prefix2.edges,
    };
    expect(ts).toEqual(py);
  });
});

describe("golden: falsifier satisfied≠refuted (Ouroboros oracle)", () => {
  it("satisfied falsifier auto-creates exactly 1 CONTRADICTS edge, 0 SUPPORTS", () => {
    const graph = reduceStream("fals", [
      { sequence: 1, type: "objective", payload: { statement: "obj" } },
      { sequence: 2, type: "hypothesis", payload: {
        claim: "hyp", falsifier: "it fails",
        objectiveId: "event:fals:1:objective",
      } },
    ] as never);

    const obsId = deriveNodeId("fals", 3, "observation");
    graph.nodes.set(obsId, {
      id: obsId, kind: NK.OBSERVATION, label: "obs",
      data: {}, confidence: null, step: null,
    });

    reduceEvent(graph, "fals", 4, "falsifier_evaluation", {
      state: "satisfied", falsifierId: "event:fals:2:falsifier",
      evidenceNodeIds: [obsId],
      explanation: "test passed but should have failed",
      evaluatorVersion: "0.13.0", evaluatedSequence: 4,
    });

    expect(getEdgesByKind(graph, EK.CONTRADICTS).length).toBe(
      golden.families.falsifier_satisfied.contradicts_count);
    expect(getEdgesByKind(graph, EK.SUPPORTS).length).toBe(
      golden.families.falsifier_satisfied.supports_count);
  });

  it("refuted falsifier creates 0 CONTRADICTS, 0 SUPPORTS", () => {
    const graph = reduceStream("fals2", [
      { sequence: 1, type: "objective", payload: { statement: "obj" } },
      { sequence: 2, type: "hypothesis", payload: {
        claim: "hyp", falsifier: "it fails",
        objectiveId: "event:fals2:1:objective",
      } },
    ] as never);

    const obsId = deriveNodeId("fals2", 3, "observation");
    graph.nodes.set(obsId, {
      id: obsId, kind: NK.OBSERVATION, label: "obs",
      data: {}, confidence: null, step: null,
    });

    reduceEvent(graph, "fals2", 4, "falsifier_evaluation", {
      state: "refuted", falsifierId: "event:fals2:2:falsifier",
      evidenceNodeIds: [obsId],
      explanation: "test failed to reproduce",
      evaluatorVersion: "0.13.0", evaluatedSequence: 4,
    });

    expect(getEdgesByKind(graph, EK.CONTRADICTS).length).toBe(
      golden.families.falsifier_refuted.contradicts_count);
    expect(getEdgesByKind(graph, EK.SUPPORTS).length).toBe(
      golden.families.falsifier_refuted.supports_count);
  });
});
