// Domain event envelope types. See docs/event-contract.md.
//
// The `events` package owns the envelope and registry mechanism only. Domain
// packages own their event *payloads*. The split between `EventDraft`
// (pre-append) and `PersistedDomainEvent` (post-append) prevents callers from
// inventing placeholder sequences, timestamps, or digests.

import type {
  EventId,
  OperationId,
  ProgramStateId,
  SessionId,
  WorkspaceId,
} from "./identity.ts";

// ---------------------------------------------------------------------------
// Producer
// ---------------------------------------------------------------------------

/**
 * Who or what produced this event. Records the category and the minimal
 * discriminator needed to interpret the event. Does not require a full
 * producer-identity system.
 */
export type EventProducer =
  | { kind: "user" }
  | { kind: "runtime"; component: string }
  | { kind: "model"; provider: string }
  | { kind: "tool"; toolName: string }
  | { kind: "projection"; projectionName: string };

// ---------------------------------------------------------------------------
// Envelope
// ---------------------------------------------------------------------------

/**
 * What a producer constructs and passes to {@link EventStore.append}. No
 * `sequence`, `recordedAt`, or `eventDigest` — those are assigned by `append`
 * and do not exist pre-append.
 */
export interface EventDraft<
  TType extends string = string,
  TPayload = unknown,
> {
  /** UUIDv7, generated by the producer before append. */
  eventId: EventId;
  /** Optional domain-level stable retry key; independently indexed. */
  idempotencyKey?: string;

  workspaceId: WorkspaceId;
  sessionId: SessionId;
  operationId?: OperationId;
  /** Optional durable Phase 1 Program ownership/correlation identity. */
  programStateId?: ProgramStateId;

  /** ISO 8601, logical time of the thing that happened. */
  occurredAt: string;

  /** e.g. `"memory.created"` — owned by the domain package. */
  type: TType;
  payload: TPayload;
  /** Per-event-type payload version. Initial version for every type is 1. */
  payloadSchemaVersion: number;

  /** Who or what caused this event. */
  producer: EventProducer;
  /** The prior event that directly caused this one, if any. */
  causationEventId?: EventId;
  /** Groups a command, model request, and resulting operations, if any. */
  correlationId?: string;
}

/**
 * What {@link EventStore.append} returns and what lives in the event log.
 * A superset of {@link EventDraft}: `append` is the only constructor.
 */
export interface PersistedDomainEvent<
  TType extends string = string,
  TPayload = unknown,
> extends EventDraft<TType, TPayload> {
  /** Monotonic per-workspace sequence, assigned by the append transaction. */
  sequence: number;
  /** ISO 8601, assigned by the append transaction. */
  recordedAt: string;
  /** SHA-256 hex over the canonical JSON of the persisted event, excluding `eventDigest`. */
  eventDigest: string;
}
